import { buildFromFactBank, roundRobinTrim } from "../lib/engine.mjs";

const D = "Codes & Standards";
const TARGET = 300;

// Note: standards are described by scope/purpose rather than specific clause numbers,
// to avoid inventing or misstating clause-level details. Well-known standard numbers
// (e.g. NFPA 13, ASHRAE 62.1) are used only where their scope is well-established and stable.
const FACTS = [
  // National Building Code (NBC)
  { term: "National Building Code (NBC) of India", topic: "National Building Code (NBC)", difficulty: "Basic", tags: ["nbc"],
    definition: "A comprehensive code published by the Bureau of Indian Standards providing guidelines for building design, construction, and services including MEP systems.",
    function: "To provide a unified reference for building design and construction practices, including fire safety, plumbing, and electrical services, across India.",
    fact: "The NBC is periodically revised and covers a wide range of topics from structural design to building services and fire safety." },
  { term: "NBC Fire and Life Safety Provisions", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc", "fire-safety"],
    definition: "Sections of the NBC addressing fire prevention, fire protection systems, and means of escape in buildings.",
    function: "To establish minimum fire safety requirements for building design, including fire fighting systems and egress.",
    fact: "NBC fire and life safety provisions are commonly referenced by local fire authorities when reviewing building plans." },
  { term: "NBC Building Services Provisions", topic: "National Building Code (NBC)", difficulty: "Basic", tags: ["nbc"],
    definition: "Sections of the NBC addressing water supply, drainage, electrical installations, and other building services.",
    function: "To provide baseline technical guidance for the design of building services such as plumbing and electrical systems.",
    fact: "NBC building services provisions are commonly used alongside relevant IS codes for detailed design." },
  { term: "Occupancy Classification (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc"],
    definition: "A system of classifying buildings by their use, such as residential, assembly, or industrial, which determines applicable safety requirements.",
    function: "To ensure fire safety and building service requirements are matched appropriately to a building's actual use and risk profile.",
    fact: "Higher-risk occupancy classifications, such as assembly or industrial buildings, typically carry more stringent fire safety requirements." },
  { term: "Means of Escape Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc", "fire-safety"],
    definition: "NBC provisions specifying requirements for travel distance, exit width, and number of exits based on occupancy and building height.",
    function: "To ensure occupants can safely evacuate a building within an acceptable time in an emergency.",
    fact: "Means of escape requirements generally become more stringent as building height and occupant load increase." },
  { term: "High-Rise Building Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Advanced", tags: ["nbc"],
    definition: "Additional fire safety and services requirements applicable to buildings above a defined height threshold.",
    function: "To address the additional fire safety and evacuation challenges posed by taller buildings.",
    fact: "High-rise buildings typically require additional fire safety measures such as refuge areas and enhanced fire fighting systems." },
  { term: "Fire NOC Requirement (NBC context)", topic: "National Building Code (NBC)", difficulty: "Basic", tags: ["nbc", "fire-safety"],
    definition: "A statutory approval confirming a building's compliance with applicable fire safety provisions before occupancy.",
    function: "To ensure independent verification that fire safety requirements have been met before a building is occupied.",
    fact: "Obtaining a fire NOC typically requires demonstrating compliance with the fire safety provisions applicable to the building's occupancy and height." },
  { term: "Car Park Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc"],
    definition: "NBC provisions addressing car park layout, ventilation, and fire safety requirements.",
    function: "To ensure car parks are designed with adequate ventilation and fire safety measures given their enclosed nature and vehicle fire risk.",
    fact: "Enclosed car parks typically require mechanical ventilation and smoke extraction provisions per applicable building code requirements." },
  { term: "Rainwater Harvesting Requirement (NBC context)", topic: "National Building Code (NBC)", difficulty: "Basic", tags: ["nbc"],
    definition: "A building code and local authority requirement mandating rainwater harvesting provisions in new construction.",
    function: "To promote groundwater recharge and water conservation as part of sustainable building design.",
    fact: "Rainwater harvesting is frequently a mandatory requirement for building plan approval in many Indian cities." },
  { term: "Accessibility Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc"],
    definition: "NBC provisions ensuring buildings are accessible to persons with disabilities, including ramps, lifts, and accessible toilets.",
    function: "To ensure buildings are usable by all occupants, including those with mobility or other disabilities.",
    fact: "Accessibility provisions commonly address ramp gradients, lift dimensions, and accessible toilet layouts." },
  { term: "Structural Fire Resistance (NBC)", topic: "National Building Code (NBC)", difficulty: "Advanced", tags: ["nbc", "fire-safety"],
    definition: "Requirements specifying the minimum fire resistance rating for structural elements and compartmentation based on occupancy and height.",
    function: "To ensure a building's structure and compartmentation can withstand fire exposure for a defined period, protecting occupants and enabling fire fighting.",
    fact: "Fire resistance ratings are typically expressed in hours and vary based on element type and building classification." },
  { term: "Ventilation Requirements (NBC)", topic: "National Building Code (NBC)", difficulty: "Basic", tags: ["nbc"],
    definition: "NBC provisions specifying minimum ventilation rates for various occupied spaces within a building.",
    function: "To ensure adequate fresh air and air quality is maintained in occupied spaces.",
    fact: "Ventilation requirements vary depending on space type, such as habitable rooms, kitchens, and toilets." },
  { term: "Water Supply and Storage Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc"],
    definition: "NBC guidelines specifying minimum water storage and supply requirements for different building occupancies.",
    function: "To ensure buildings have an adequate and reliable water supply for both domestic and fire fighting needs.",
    fact: "NBC water supply provisions are typically read together with the relevant IS codes for detailed water demand calculation." },
  { term: "Lift Provisions (NBC)", topic: "National Building Code (NBC)", difficulty: "Intermediate", tags: ["nbc"],
    definition: "NBC provisions specifying requirements for the number, capacity, and safety features of lifts based on building height and occupancy.",
    function: "To ensure adequate vertical transportation capacity and safety for building occupants.",
    fact: "Lift provisions typically require lift lobbies to be part of a protected escape route in taller buildings." },
  { term: "Setback and Fire Tender Access (NBC)", topic: "National Building Code (NBC)", difficulty: "Advanced", tags: ["nbc", "fire-safety"],
    definition: "NBC provisions specifying minimum open space or setback around a building to allow fire tender access and operation.",
    function: "To ensure fire tenders can approach and operate around a building during a fire emergency.",
    fact: "Adequate fire tender access and turning space is a common requirement for taller or larger buildings under the NBC." },

  // Indian Standards (IS Codes)
  { term: "IS Code for Electrical Wiring Installations", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "An Indian Standard code of practice providing guidelines for the design and installation of electrical wiring in buildings.",
    function: "To provide a technical reference ensuring safe and standardized electrical wiring practices in Indian buildings.",
    fact: "Indian Standard codes of practice for electrical wiring cover aspects such as conductor sizing, protection, and earthing requirements." },
  { term: "IS Code for Earthing Practice", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "An Indian Standard code of practice providing guidelines for the design and installation of earthing systems in electrical installations.",
    function: "To ensure earthing systems are designed and installed to provide effective protection against electric shock and equipment damage.",
    fact: "Indian earthing practice standards address aspects such as earth electrode design, earth resistance values, and conductor sizing." },
  { term: "IS Code for GI Pipes", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "An Indian Standard specifying the material, dimensions, and quality requirements for galvanized iron pipes.",
    function: "To ensure GI pipes used in plumbing and other applications meet consistent quality and dimensional standards.",
    fact: "Indian Standards for GI pipes specify parameters such as wall thickness, galvanizing quality, and pipe classes." },
  { term: "IS Code for Fire Extinguishers", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "Indian Standards specifying the construction, performance, and maintenance requirements for portable fire extinguishers.",
    function: "To ensure fire extinguishers manufactured and used in India meet minimum performance and safety requirements.",
    fact: "Indian Standards for fire extinguishers address aspects such as extinguishing capacity ratings and periodic maintenance requirements." },
  { term: "IS Code for Fire Detection and Alarm Systems", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "An Indian Standard code of practice covering the design, installation, and maintenance of automatic fire detection and alarm systems.",
    function: "To ensure fire alarm systems in India are designed and installed to provide reliable, timely fire detection.",
    fact: "This code of practice addresses aspects such as detector spacing, zoning, and system testing requirements." },
  { term: "IS Code for Sprinkler Systems", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "An Indian Standard code of practice covering the design and installation of automatic sprinkler fire suppression systems.",
    function: "To ensure sprinkler systems installed in India meet minimum design and performance requirements for effective fire suppression.",
    fact: "This code addresses aspects such as sprinkler spacing, water supply requirements, and system components." },
  { term: "IS Code for Water Supply Fixtures", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "Indian Standards specifying dimensional and quality requirements for plumbing fixtures such as wash basins and water closets.",
    function: "To ensure plumbing fixtures manufactured in India meet consistent quality and dimensional standards.",
    fact: "These standards help ensure interoperability and consistent quality across plumbing fixtures from different manufacturers." },
  { term: "IS Code for Cables", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "Indian Standards specifying construction, insulation, and testing requirements for power and control cables.",
    function: "To ensure cables manufactured and used in India meet minimum safety and performance requirements.",
    fact: "Indian cable standards address aspects such as conductor material, insulation type, and voltage grade testing." },
  { term: "Bureau of Indian Standards (BIS)", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "The national standards body of India responsible for developing and publishing Indian Standards, including many relevant to MEP works.",
    function: "To develop, publish, and maintain national standards ensuring quality and safety across Indian industry, including construction and MEP.",
    fact: "BIS certification and standards are widely referenced in Indian MEP specifications and tender documents." },
  { term: "IS Code for Air Conditioning and Ventilation", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "An Indian Standard code of practice addressing the design of air conditioning and mechanical ventilation systems.",
    function: "To provide design guidance ensuring HVAC systems in India meet baseline performance and safety expectations.",
    fact: "This code of practice covers aspects such as design conditions, ventilation rates, and basic system design principles." },
  { term: "IS Code for DG Set Installation", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "An Indian Standard code of practice covering the installation requirements for diesel generator sets.",
    function: "To ensure DG set installations in India meet safety and performance requirements, including exhaust and noise considerations.",
    fact: "This code addresses aspects such as DG room ventilation, exhaust piping, and acoustic enclosure requirements." },
  { term: "IS Code for Lightning Protection", topic: "Indian Standards (IS Codes)", difficulty: "Advanced", tags: ["is-code"],
    definition: "An Indian Standard code of practice covering the design of lightning protection systems for buildings and structures.",
    function: "To ensure lightning protection systems in India are designed to effectively protect structures and occupants from lightning strikes.",
    fact: "This code addresses aspects such as risk assessment, air termination design, and earthing requirements for lightning protection." },
  { term: "IS Code for Water Tanks", topic: "Indian Standards (IS Codes)", difficulty: "Basic", tags: ["is-code"],
    definition: "Indian Standards addressing the design, material, and construction requirements for water storage tanks.",
    function: "To ensure water storage tanks used in buildings meet minimum quality, hygiene, and structural requirements.",
    fact: "These standards cover both underground and overhead tank construction in various materials, including RCC and plastic." },
  { term: "IS Code for Pumps", topic: "Indian Standards (IS Codes)", difficulty: "Intermediate", tags: ["is-code"],
    definition: "Indian Standards specifying performance testing and construction requirements for centrifugal pumps used in water supply and fire fighting.",
    function: "To ensure pumps used in Indian building services meet minimum performance and quality benchmarks.",
    fact: "Indian pump standards typically specify performance testing procedures to verify flow and head ratings claimed by manufacturers." },
  { term: "IS Code for Switchgear and Panels", topic: "Indian Standards (IS Codes)", difficulty: "Advanced", tags: ["is-code"],
    definition: "Indian Standards specifying construction, testing, and safety requirements for low voltage switchgear and control panels.",
    function: "To ensure electrical panels manufactured and installed in India meet minimum safety and performance requirements.",
    fact: "These standards address aspects such as type testing, degree of protection, and internal segregation of panels." },

  // International Standards (IEC/IEEE/NEC)
  { term: "IEC Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Basic", tags: ["iec"],
    definition: "Internationally recognized standards published by the International Electrotechnical Commission, covering electrical, electronic, and related technologies.",
    function: "To provide a common international technical reference for electrical equipment design, testing, and safety.",
    fact: "Many Indian and international electrical equipment standards are harmonized with or based on corresponding IEC standards." },
  { term: "IEEE Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["ieee"],
    definition: "Standards developed by the Institute of Electrical and Electronics Engineers, covering a wide range of electrical and electronics topics.",
    function: "To provide technical standards and guidelines widely referenced in power systems engineering and other electrical fields.",
    fact: "IEEE standards are commonly referenced in power system studies, such as harmonic analysis and protection coordination." },
  { term: "NEC (National Electrical Code, US)", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["nec"],
    definition: "A US-based model electrical code providing safety standards for electrical wiring and equipment installation.",
    function: "To provide a widely referenced model code for safe electrical installation practices, influential even outside the United States.",
    fact: "While NEC is a US code, its concepts and terminology are often referenced informally in international MEP discussions." },
  { term: "IP Rating Standard (IEC 60529)", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Basic", tags: ["iec"],
    definition: "An IEC standard classification system, such as IP54 or IP65, indicating an enclosure's degree of protection against dust and water.",
    function: "To provide an internationally recognized way of specifying enclosure protection levels for electrical equipment.",
    fact: "IP ratings are widely used internationally, including in Indian MEP specifications, to define required enclosure protection." },
  { term: "IEC Cable and Insulation Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["iec"],
    definition: "IEC standards specifying construction, insulation, and testing requirements for power cables used internationally.",
    function: "To provide a common international reference for cable quality and performance, supporting global equipment specification.",
    fact: "International projects often specify cables to IEC standards to ensure consistency across different supplier countries." },
  { term: "ISO 9001 (Quality Management)", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Basic", tags: ["iso"],
    definition: "An international standard specifying requirements for a quality management system used by organizations, including MEP contractors and manufacturers.",
    function: "To ensure organizations have consistent processes in place to deliver products and services meeting quality requirements.",
    fact: "ISO 9001 certification is commonly required as a prequalification criterion for MEP contractors and equipment suppliers in tenders." },
  { term: "IEC Switchgear Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Advanced", tags: ["iec"],
    definition: "IEC standards specifying design, testing, and safety requirements for low and high voltage switchgear.",
    function: "To ensure switchgear used internationally meets consistent safety and performance benchmarks.",
    fact: "IEC switchgear standards are widely referenced for type testing requirements of panels, breakers, and switchgear assemblies." },
  { term: "IEC Motor Efficiency Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["iec"],
    definition: "IEC standards specifying performance, efficiency, and construction requirements for electric motors.",
    function: "To ensure motors used internationally meet consistent efficiency and performance benchmarks.",
    fact: "IEC motor efficiency classes, such as IE2 and IE3, are commonly referenced in specifications to define minimum motor efficiency." },
  { term: "ASME Standards", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["asme"],
    definition: "Standards developed by the American Society of Mechanical Engineers, covering mechanical engineering topics including pressure vessels and piping.",
    function: "To provide widely recognized technical standards for the design and construction of mechanical equipment such as pressure vessels.",
    fact: "ASME standards are commonly referenced for pressure vessel and piping design in HVAC and fire fighting systems." },
  { term: "IEC Harmonics Emission Standard", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Advanced", tags: ["iec"],
    definition: "An IEC standard addressing limits for harmonic current emissions from electrical equipment.",
    function: "To limit harmonic pollution injected into the electrical supply network by connected equipment.",
    fact: "Harmonic emission limit standards help protect power quality in shared electrical distribution networks." },
  { term: "Electrical Safety Standards for Personnel", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Advanced", tags: ["safety"],
    definition: "International standards addressing electrical safety practices and protective equipment for work on or near live electrical equipment.",
    function: "To establish safe working practices and PPE requirements protecting personnel from electrical hazards including arc flash.",
    fact: "These standards typically inform the selection of appropriate PPE categories based on assessed arc flash risk." },
  { term: "International Standards Harmonization", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["iec"],
    definition: "The practice of aligning national standards, such as Indian Standards, with corresponding international standards like IEC, to support global trade.",
    function: "To reduce technical barriers and ensure equipment designed to one recognized standard is broadly acceptable internationally.",
    fact: "Many Indian Standards for electrical equipment are technically aligned with or adapted from corresponding IEC standards." },
  { term: "UL (Underwriters Laboratories) Listing", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["ul"],
    definition: "A US-based product safety certification indicating that an item has been tested and meets defined safety requirements.",
    function: "To provide assurance that electrical and fire safety equipment meets recognized independent safety testing standards.",
    fact: "UL-listed equipment, such as fire pumps and electrical devices, is frequently specified or accepted in addition to local certifications." },
  { term: "FM (Factory Mutual) Approval", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Intermediate", tags: ["fm-approval"],
    definition: "A certification indicating that fire protection equipment, such as sprinklers or fire pumps, has been tested and approved by FM Global.",
    function: "To provide insurers and clients assurance that fire protection equipment meets recognized performance and reliability benchmarks.",
    fact: "FM approval is commonly specified for fire protection equipment on insurance-driven or multinational projects." },
  { term: "CE Marking", topic: "International Standards (IEC/IEEE/NEC)", difficulty: "Basic", tags: ["ce-marking"],
    definition: "A marking indicating a product complies with applicable European Union health, safety, and environmental protection standards.",
    function: "To indicate regulatory compliance for products sold or used within the European Economic Area.",
    fact: "CE marking is sometimes referenced on imported MEP equipment even in non-European projects as a general quality indicator." },

  // Fire Codes (NFPA)
  { term: "NFPA (National Fire Protection Association) Codes", topic: "Fire Codes (NFPA)", difficulty: "Basic", tags: ["nfpa"],
    definition: "A US-based organization publishing widely referenced fire safety codes and standards, often used as a reference internationally.",
    function: "To provide comprehensive, technically detailed fire safety standards referenced globally in the absence of more specific local codes.",
    fact: "NFPA codes and standards are widely referenced internationally for fire protection system design, even outside the United States." },
  { term: "NFPA 13 (Sprinkler Systems)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "An NFPA standard for the design and installation of automatic fire sprinkler systems.",
    function: "To provide detailed technical requirements for sprinkler system design, ensuring effective fire suppression performance.",
    fact: "NFPA 13 is one of the most widely referenced international standards for sprinkler system design." },
  { term: "NFPA 20 (Fire Pumps)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "An NFPA standard for the installation of stationary fire pumps for fire protection systems.",
    function: "To provide detailed technical requirements for fire pump selection, installation, and testing.",
    fact: "NFPA 20 is commonly referenced internationally for fire pump sizing, controller requirements, and acceptance testing." },
  { term: "NFPA 72 (Fire Alarm and Signaling)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "An NFPA standard covering the application, installation, and testing of fire alarm and signaling systems.",
    function: "To provide detailed technical requirements ensuring reliable fire detection and notification system performance.",
    fact: "NFPA 72 is commonly referenced internationally for fire alarm system design and testing requirements." },
  { term: "NFPA 101 (Life Safety Code)", topic: "Fire Codes (NFPA)", difficulty: "Advanced", tags: ["nfpa"],
    definition: "An NFPA code addressing life safety requirements for building design, including means of egress.",
    function: "To provide comprehensive life safety requirements addressing occupant evacuation and protection during a fire.",
    fact: "NFPA 101 is widely referenced internationally for means of egress and life safety design principles." },
  { term: "Hazard Classification (Fire Codes)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "A classification system, such as light, ordinary, or extra hazard, used to determine appropriate fire protection design parameters for an occupancy.",
    function: "To match the level of fire protection provided, such as sprinkler density, to the actual fire risk of an occupancy.",
    fact: "Higher hazard classifications typically require greater sprinkler density and water supply duration." },
  { term: "NFPA 2001 (Clean Agent Systems)", topic: "Fire Codes (NFPA)", difficulty: "Advanced", tags: ["nfpa"],
    definition: "An NFPA standard covering the design, installation, and testing of clean agent fire extinguishing systems.",
    function: "To provide detailed technical requirements ensuring clean agent systems effectively suppress fires in sensitive equipment areas.",
    fact: "NFPA 2001 is commonly referenced for the design of clean agent suppression systems protecting data centers and electrical rooms." },
  { term: "NFPA 12 (CO2 Systems)", topic: "Fire Codes (NFPA)", difficulty: "Advanced", tags: ["nfpa"],
    definition: "An NFPA standard covering the design, installation, and use of carbon dioxide fire extinguishing systems.",
    function: "To provide detailed technical requirements ensuring CO2 suppression systems are designed and operated safely and effectively.",
    fact: "NFPA 12 includes specific safety provisions addressing the asphyxiation hazard posed by CO2 systems to personnel." },
  { term: "NFPA 25 (ITM of Water-Based Systems)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "An NFPA standard covering the inspection, testing, and maintenance of water-based fire protection systems.",
    function: "To ensure water-based fire protection systems remain functional and reliable throughout their service life.",
    fact: "NFPA 25 establishes recommended inspection and testing frequencies for components such as sprinklers, valves, and fire pumps." },
  { term: "Fire Hazard Occupancy Classification", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "A general framework classifying occupancies by fire risk, guiding the selection of appropriate fire protection systems.",
    function: "To ensure fire protection system design, such as sprinkler type and density, matches the actual fire risk of an occupancy's contents.",
    fact: "Storage occupancies with high combustible loads typically require more robust fire protection than light-hazard office occupancies." },
  { term: "NFPA 14 (Standpipe Systems)", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["nfpa"],
    definition: "An NFPA standard covering the design and installation of standpipe and hose systems in buildings.",
    function: "To provide detailed technical requirements for standpipe system design, similar in intent to wet riser systems in other codes.",
    fact: "NFPA 14 is commonly referenced internationally alongside local hydrant/standpipe code requirements for high-rise buildings." },
  { term: "NFPA 92 (Smoke Control Systems)", topic: "Fire Codes (NFPA)", difficulty: "Advanced", tags: ["nfpa"],
    definition: "An NFPA standard covering the design of smoke control systems, including pressurization and smoke management systems.",
    function: "To provide detailed technical requirements ensuring smoke control systems perform effectively during a fire.",
    fact: "NFPA 92 is commonly referenced for the design of staircase pressurization and atrium smoke management systems." },
  { term: "Fire Risk Assessment", topic: "Fire Codes (NFPA)", difficulty: "Intermediate", tags: ["fire-safety"],
    definition: "A systematic evaluation of a building's fire hazards and the adequacy of its fire safety measures.",
    function: "To identify fire risks and verify that appropriate fire prevention and protection measures are in place.",
    fact: "Fire risk assessments are often required periodically for existing buildings, in addition to code compliance at the design stage." },

  // HVAC Standards (ASHRAE/SMACNA)
  { term: "ASHRAE", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Basic", tags: ["ashrae"],
    definition: "The American Society of Heating, Refrigerating and Air-Conditioning Engineers, a professional society publishing widely referenced HVAC standards.",
    function: "To provide technical standards and design guidance referenced globally for HVAC system design and performance.",
    fact: "ASHRAE standards and handbooks are widely referenced internationally for HVAC load calculation and design practice." },
  { term: "ASHRAE 62.1 (Ventilation)", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["ashrae"],
    definition: "An ASHRAE standard specifying minimum ventilation rates for acceptable indoor air quality in commercial buildings.",
    function: "To ensure buildings provide adequate outdoor air ventilation to maintain acceptable indoor air quality.",
    fact: "ASHRAE 62.1 is commonly referenced internationally for determining minimum fresh air ventilation rates." },
  { term: "ASHRAE 90.1 (Energy Standard)", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["ashrae"],
    definition: "An ASHRAE standard specifying minimum energy efficiency requirements for buildings, including HVAC systems.",
    function: "To promote energy-efficient building design by establishing minimum performance requirements for building systems.",
    fact: "ASHRAE 90.1 is widely referenced internationally as a baseline for building energy efficiency requirements." },
  { term: "SMACNA", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Basic", tags: ["smacna"],
    definition: "The Sheet Metal and Air Conditioning Contractors' National Association, publishing widely referenced ductwork construction standards.",
    function: "To provide standardized guidance for ductwork fabrication, reinforcement, and installation quality.",
    fact: "SMACNA duct construction standards are widely referenced internationally for ductwork fabrication and installation practices." },
  { term: "ASHRAE 55 (Thermal Comfort)", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["ashrae"],
    definition: "An ASHRAE standard specifying conditions for acceptable thermal comfort for building occupants.",
    function: "To provide design guidance ensuring indoor temperature and humidity conditions are comfortable for the majority of occupants.",
    fact: "ASHRAE thermal comfort standards consider factors such as temperature, humidity, air speed, and occupant clothing and activity level." },
  { term: "SMACNA Duct Leakage Guidelines", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Advanced", tags: ["smacna"],
    definition: "SMACNA guidelines specifying allowable duct leakage rates based on duct construction pressure class.",
    function: "To ensure ductwork is constructed and sealed to limit air leakage within acceptable, class-appropriate limits.",
    fact: "Higher pressure class ductwork typically has stricter allowable leakage limits under SMACNA guidelines." },
  { term: "ASHRAE 15 (Refrigerant Safety)", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Advanced", tags: ["ashrae"],
    definition: "An ASHRAE standard addressing the safe design and operation of refrigeration systems, including refrigerant classification and ventilation.",
    function: "To ensure refrigeration systems are designed with adequate safety measures appropriate to the refrigerant's toxicity and flammability classification.",
    fact: "This standard influences requirements such as machine room ventilation and refrigerant detection based on refrigerant safety classification." },
  { term: "Green Building Rating Standards (LEED/IGBC)", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["green-building"],
    definition: "Voluntary rating systems, such as LEED or IGBC, that assess a building's sustainability performance, including energy and water efficiency.",
    function: "To provide a recognized framework and certification for evaluating and demonstrating a building's environmental performance.",
    fact: "Green building rating systems often award credits for measures such as energy-efficient HVAC design and water conservation." },
  { term: "Indoor Air Quality (IAQ) Standards", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["iaq"],
    definition: "Standards and guidelines addressing acceptable levels of contaminants and ventilation to maintain good indoor air quality.",
    function: "To protect occupant health and comfort by controlling indoor air contaminants and ensuring adequate ventilation.",
    fact: "IAQ standards commonly influence minimum outdoor air ventilation rates and filtration requirements in HVAC design." },
  { term: "Energy Conservation Building Code (ECBC), India", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Intermediate", tags: ["ecbc"],
    definition: "An Indian code specifying minimum energy efficiency requirements for commercial buildings, including HVAC and lighting systems.",
    function: "To promote energy-efficient building design in India by establishing minimum performance requirements for building systems.",
    fact: "ECBC compliance is increasingly required or incentivized for commercial building approvals in India." },
  { term: "Refrigerant Phase-Down Regulations", topic: "HVAC Standards (ASHRAE/SMACNA)", difficulty: "Advanced", tags: ["refrigerant"],
    definition: "International and national regulations progressively restricting the use of high global-warming-potential refrigerants.",
    function: "To reduce the environmental impact of refrigerants used in air conditioning and refrigeration systems over time.",
    fact: "Refrigerant phase-down regulations are gradually driving the HVAC industry toward lower-GWP refrigerant alternatives." },

  // Electrical Safety Standards
  { term: "Electrical Safety Regulations", topic: "Electrical Safety Standards", difficulty: "Basic", tags: ["electrical-safety"],
    definition: "Statutory regulations governing safe electrical installation, operation, and maintenance practices to protect life and property.",
    function: "To establish minimum mandatory safety requirements for electrical installations and their operation.",
    fact: "Electrical safety regulations typically address aspects such as earthing, protection against shock, and safe working practices." },
  { term: "Arc Flash Safety Standard", topic: "Electrical Safety Standards", difficulty: "Advanced", tags: ["electrical-safety"],
    definition: "A standard addressing electrical safety in the workplace, including arc flash hazard analysis and required protective measures.",
    function: "To reduce the risk of injury to personnel working on or near energized electrical equipment.",
    fact: "Arc flash safety standards typically require hazard analysis to determine appropriate PPE and safe approach boundaries." },
  { term: "Permit to Work System", topic: "Electrical Safety Standards", difficulty: "Basic", tags: ["electrical-safety"],
    definition: "A formal, documented safety management system authorizing specific work on equipment after required precautions are confirmed.",
    function: "To ensure hazards are systematically identified and controlled before potentially hazardous work begins.",
    fact: "Permit to work systems are widely used across MEP disciplines for work involving electrical isolation, confined spaces, or work at height." },
  { term: "Lockout-Tagout Standard", topic: "Electrical Safety Standards", difficulty: "Intermediate", tags: ["electrical-safety"],
    definition: "A standardized safety procedure and set of practices for isolating and securing equipment before maintenance work.",
    function: "To prevent accidental re-energization of equipment during maintenance, protecting personnel from injury.",
    fact: "Lockout-tagout practices typically require each worker to apply and control their own personal lock during isolation." },
  { term: "Earthing and Bonding Safety Requirements", topic: "Electrical Safety Standards", difficulty: "Intermediate", tags: ["electrical-safety"],
    definition: "Regulatory and standard requirements specifying minimum earthing and bonding provisions to protect against electric shock.",
    function: "To ensure electrical installations provide an effective path for fault current, minimizing shock risk to occupants.",
    fact: "Earthing and bonding requirements are among the most fundamental electrical safety provisions in any electrical code or standard." },
  { term: "Electrical Installation Testing Standard", topic: "Electrical Safety Standards", difficulty: "Intermediate", tags: ["electrical-safety"],
    definition: "Standards specifying the tests, such as insulation resistance and earth continuity, required to verify a new electrical installation before energization.",
    function: "To confirm an electrical installation is safe to energize and free from installation defects.",
    fact: "Initial verification testing typically includes insulation resistance, earth continuity, and polarity checks before an installation is energized." },
  { term: "PPE Standards for Electrical Work", topic: "Electrical Safety Standards", difficulty: "Basic", tags: ["electrical-safety"],
    definition: "Standards specifying the required protective equipment, such as insulated gloves and arc-rated clothing, for electrical work.",
    function: "To ensure personnel are adequately protected from shock and arc flash hazards while performing electrical work.",
    fact: "PPE requirements for electrical work are typically matched to the specific hazard level determined by a risk assessment." },
  { term: "Statutory Electrical Inspection", topic: "Electrical Safety Standards", difficulty: "Intermediate", tags: ["electrical-safety"],
    definition: "A mandatory inspection by a government electrical inspector to approve high-voltage or large electrical installations before energization.",
    function: "To ensure electrical installations meet statutory safety requirements before being connected to supply, particularly for HT installations.",
    fact: "Statutory electrical inspection and approval is commonly required before energizing HT installations or large DG sets in many jurisdictions." },
  { term: "Electrical Load Sanction", topic: "Electrical Safety Standards", difficulty: "Basic", tags: ["electrical-safety"],
    definition: "A formal approval from the electricity distribution utility authorizing a specific connected load for a building.",
    function: "To ensure the utility's distribution network can support the building's intended electrical demand before connection.",
    fact: "Electrical load sanction is typically required before a permanent power connection is provided to a new building." },
  { term: "Hazardous Area Classification", topic: "Electrical Safety Standards", difficulty: "Advanced", tags: ["electrical-safety"],
    definition: "A system classifying areas based on the likelihood of flammable gas, vapor, or dust presence, determining appropriate equipment selection.",
    function: "To ensure electrical equipment installed in potentially explosive atmospheres is suitably rated to prevent ignition.",
    fact: "Hazardous area classification determines whether flameproof or intrinsically safe electrical equipment is required in a given area." },

  // Testing & Inspection Requirements
  { term: "Factory Acceptance Test (FAT)", topic: "Testing & Inspection Requirements", difficulty: "Intermediate", tags: ["testing"],
    definition: "A test conducted at the manufacturer's facility to verify equipment functions and performs correctly before shipment to site.",
    function: "To identify and resolve defects before equipment is shipped, reducing the risk of site-based rework.",
    fact: "FATs are commonly witnessed by the client or consultant for major equipment such as transformers, panels, and chillers." },
  { term: "Site Acceptance Test (SAT)", topic: "Testing & Inspection Requirements", difficulty: "Intermediate", tags: ["testing"],
    definition: "A test conducted at the installation site to verify equipment functions correctly after installation, prior to commissioning.",
    function: "To confirm equipment has been installed correctly and functions as intended in its actual operating environment.",
    fact: "SATs are typically conducted after installation but before an equipment is handed over for operational use." },
  { term: "Third-Party Inspection Agency", topic: "Testing & Inspection Requirements", difficulty: "Basic", tags: ["testing"],
    definition: "An independent organization engaged to inspect and certify that installed systems comply with design and code requirements.",
    function: "To provide independent, unbiased verification of compliance, often required by insurers or statutory authorities.",
    fact: "Third-party inspection is commonly mandated for critical systems such as fire fighting, pressure vessels, and lifts." },
  { term: "Pre-Commissioning Checks", topic: "Testing & Inspection Requirements", difficulty: "Basic", tags: ["testing"],
    definition: "A series of checks performed on installed systems before functional testing, verifying installation is complete and safe to energize or operate.",
    function: "To catch installation errors and safety issues before equipment is energized or put into functional operation.",
    fact: "Pre-commissioning checks typically include visual inspection, continuity checks, and verification against approved drawings." },
  { term: "Functional Performance Testing", topic: "Testing & Inspection Requirements", difficulty: "Intermediate", tags: ["testing"],
    definition: "Testing that verifies a system operates according to its intended design sequence and performance criteria under actual operating conditions.",
    function: "To confirm that a system not only operates but performs its intended function correctly under realistic conditions.",
    fact: "Functional performance testing typically follows successful pre-commissioning checks and precedes final system handover." },
  { term: "Integrated Systems Testing", topic: "Testing & Inspection Requirements", difficulty: "Advanced", tags: ["testing"],
    definition: "Testing that verifies multiple interconnected systems, such as fire alarm and HVAC, work together correctly during an event such as a fire.",
    function: "To confirm that cross-system interactions, such as HVAC shutdown on fire alarm activation, function as designed.",
    fact: "Integrated systems testing is particularly important for life-safety interlocks between fire alarm, HVAC, and access control systems." },
  { term: "Snag List / Punch List", topic: "Testing & Inspection Requirements", difficulty: "Basic", tags: ["testing"],
    definition: "A documented list of defects or incomplete items identified during inspection, to be rectified before final handover.",
    function: "To systematically track and ensure resolution of outstanding defects before a project or system is formally handed over.",
    fact: "Snag lists are typically reviewed and closed out jointly by the contractor and consultant before final handover." },
  { term: "Defect Liability Period (DLP)", topic: "Testing & Inspection Requirements", difficulty: "Intermediate", tags: ["testing"],
    definition: "A period after project completion during which the contractor remains responsible for rectifying defects that arise in their work.",
    function: "To provide the client assurance that defects appearing after handover will be rectified by the contractor at no additional cost.",
    fact: "The defect liability period typically begins from the date of substantial completion or handover of the works." },
  { term: "Witness Testing", topic: "Testing & Inspection Requirements", difficulty: "Intermediate", tags: ["testing"],
    definition: "Testing conducted in the presence of the client, consultant, or third-party inspector to independently verify results.",
    function: "To provide independent assurance that test results are genuine and equipment performs as claimed.",
    fact: "Witness testing is commonly required for critical equipment such as transformers, fire pumps, and generators." },
  { term: "Non-Destructive Testing (NDT)", topic: "Testing & Inspection Requirements", difficulty: "Advanced", tags: ["testing"],
    definition: "Testing methods, such as radiography or ultrasonic testing, used to examine welds or materials without damaging them.",
    function: "To verify the quality of welded joints and materials, such as fire fighting or high-pressure piping, without destroying the tested item.",
    fact: "NDT methods are commonly specified for critical welded joints in fire fighting mains and pressure piping systems." },
  { term: "Test Certificate", topic: "Testing & Inspection Requirements", difficulty: "Basic", tags: ["testing"],
    definition: "A formal document recording the results of a test performed on equipment or an installation, confirming compliance with specified criteria.",
    function: "To provide documented evidence that equipment or an installation has been tested and meets required performance criteria.",
    fact: "Test certificates are typically compiled as part of the final handover documentation for a project." },

  // MEP Coordination Practices
  { term: "MEP Coordination", topic: "MEP Coordination Practices", difficulty: "Basic", tags: ["coordination"],
    definition: "The process of resolving clashes and ensuring proper integration between mechanical, electrical, and plumbing systems during design and construction.",
    function: "To prevent physical clashes and ensure all MEP systems fit together correctly within the available space.",
    fact: "MEP coordination is increasingly performed using 3D BIM models to identify and resolve clashes before construction." },
  { term: "BIM (Building Information Modeling)", topic: "MEP Coordination Practices", difficulty: "Intermediate", tags: ["bim"],
    definition: "A digital process of creating and managing 3D models of a building's physical and functional characteristics, including MEP systems.",
    function: "To enable better visualization, clash detection, and coordination between different building disciplines before construction.",
    fact: "BIM-based clash detection helps identify conflicts between MEP services and structural or architectural elements before site execution." },
  { term: "Clash Detection", topic: "MEP Coordination Practices", difficulty: "Intermediate", tags: ["bim"],
    definition: "The process of identifying physical conflicts between different building elements, such as ducts and structural beams, using coordinated 3D models.",
    function: "To identify and resolve spatial conflicts between different systems before they become costly site problems.",
    fact: "Clash detection is typically performed iteratively throughout the design and coordination process, not just once." },
  { term: "Services Coordination Drawing", topic: "MEP Coordination Practices", difficulty: "Basic", tags: ["coordination"],
    definition: "A drawing showing the coordinated routing of multiple MEP services within a common space, resolving potential clashes.",
    function: "To provide a single reference drawing showing how different services are routed together without conflict.",
    fact: "Coordinated services drawings are typically issued for construction only after all disciplines have reviewed and resolved clashes." },
  { term: "Builder's Work (BW) Drawing", topic: "MEP Coordination Practices", difficulty: "Intermediate", tags: ["coordination"],
    definition: "A drawing indicating openings, chases, and inserts required in structural and architectural elements for MEP services.",
    function: "To ensure civil and structural contractors provide the necessary openings and provisions for MEP services in a timely manner.",
    fact: "Builder's work drawings must typically be issued well in advance of concrete pours to avoid costly rework." },
  { term: "Interface Management", topic: "MEP Coordination Practices", difficulty: "Advanced", tags: ["coordination"],
    definition: "The process of managing responsibilities and information exchange at the boundaries between different contractors' scopes of work.",
    function: "To ensure smooth coordination and avoid gaps or overlaps in responsibility at the interfaces between different trade packages.",
    fact: "Poor interface management is a common source of coordination disputes and delays on MEP projects." },
  { term: "Handover Documentation", topic: "MEP Coordination Practices", difficulty: "Basic", tags: ["coordination"],
    definition: "The complete set of documents, including as-built drawings, O&M manuals, and test certificates, provided to the client at project completion.",
    function: "To ensure the client has all information needed to operate and maintain the installed systems after handover.",
    fact: "Handover documentation typically includes O&M manuals, as-built drawings, warranty certificates, and test/commissioning records." },
  { term: "Request for Information (RFI)", topic: "MEP Coordination Practices", difficulty: "Basic", tags: ["coordination"],
    definition: "A formal query raised during construction seeking clarification on a design or specification ambiguity.",
    function: "To formally document and resolve ambiguities or conflicts discovered during construction execution.",
    fact: "RFIs are typically logged and tracked to ensure timely responses that do not delay construction progress." },
  { term: "Design Basis Report (DBR)", topic: "MEP Coordination Practices", difficulty: "Intermediate", tags: ["coordination"],
    definition: "A document explaining the design assumptions, criteria, and calculations underlying an MEP system's design.",
    function: "To provide a documented rationale for design decisions, supporting review, approval, and future reference.",
    fact: "A design basis report is commonly required at key design stages for review by the client or statutory authorities." },
  { term: "Value Engineering", topic: "MEP Coordination Practices", difficulty: "Intermediate", tags: ["coordination"],
    definition: "A systematic process of reviewing a design to reduce cost or improve value without compromising essential function or quality.",
    function: "To identify opportunities for cost savings or performance improvement while maintaining the design's core functional intent.",
    fact: "Value engineering exercises should be carefully reviewed to ensure proposed changes do not compromise safety or code compliance." },
];

export function generateCodes() {
  const conceptual = roundRobinTrim(buildFromFactBank(FACTS, D), TARGET, (q) => q.topic);
  return conceptual.slice(0, TARGET);
}

export { FACTS };
