import { randInt, randFloat, pick } from "../lib/rng.mjs";
import { buildFromFactBank, buildCalcSet, roundRobinTrim } from "../lib/engine.mjs";

const D = "Plumbing";
const TARGET = 500;
const CONCEPTUAL_TARGET = 130;

const FACTS = [
  // Domestic Water Supply
  { term: "Cold Water Supply System", topic: "Domestic Water Supply", difficulty: "Basic", tags: ["water-supply"],
    definition: "A plumbing system that supplies unheated potable water to fixtures and outlets throughout a building.",
    function: "To provide a reliable, adequate supply of potable water for drinking, washing, and general use.",
    fact: "Cold water systems are typically designed considering peak demand, simultaneous usage, and adequate residual pressure at fixtures." },
  { term: "Hot Water Supply System", topic: "Domestic Water Supply", difficulty: "Basic", tags: ["water-supply"],
    definition: "A plumbing system that supplies heated water to fixtures, typically generated by water heaters or a central hot water plant.",
    function: "To provide heated water for bathing, washing, and other uses requiring warm water.",
    fact: "Hot water systems may be either centralized, with a common generation plant, or localized, with individual water heaters." },
  { term: "Water Supply Riser", topic: "Domestic Water Supply", difficulty: "Intermediate", tags: ["water-supply"],
    definition: "A vertical pipe distributing water supply from a source, such as a pump or tank, to multiple floors of a building.",
    function: "To distribute water vertically through a multi-storey building to floor-wise distribution branches.",
    fact: "Water supply risers are typically sized to maintain adequate pressure and flow at the topmost served floor." },
  { term: "Potable Water", topic: "Domestic Water Supply", difficulty: "Basic", tags: ["water-supply"],
    definition: "Water that is safe and suitable for human consumption and general domestic use.",
    function: "To distinguish drinking-quality water from non-potable water used for flushing or landscaping.",
    fact: "Potable water systems must be protected from cross-connection with non-potable sources such as flush water or STP-treated water." },
  { term: "Cross Connection Control", topic: "Domestic Water Supply", difficulty: "Advanced", tags: ["water-supply"],
    definition: "Measures such as backflow preventers used to prevent contamination of the potable water supply by non-potable water sources.",
    function: "To protect the potable water supply from contamination due to backflow or back-siphonage.",
    fact: "Backflow preventers are commonly required at connections where potable water could be contaminated, such as at RO plants or irrigation systems." },
  { term: "Water Meter", topic: "Domestic Water Supply", difficulty: "Basic", tags: ["water-supply"],
    definition: "A device that measures the volume of water passing through a supply pipe, used for billing or monitoring purposes.",
    function: "To measure water consumption for billing, sub-metering, or leak detection purposes.",
    fact: "Water meters are commonly installed at the point of entry to a building or at individual sub-metered units." },

  // Water Storage & Pumping Systems
  { term: "Underground Water Tank", topic: "Water Storage & Pumping Systems", difficulty: "Basic", tags: ["storage"],
    definition: "A water storage tank constructed below ground level, typically used to store the primary incoming water supply.",
    function: "To provide a buffer storage of water between the municipal or source supply and the building's distribution system.",
    fact: "Underground tanks are typically sized to provide at least one day's water storage, in addition to fire reserve where combined." },
  { term: "Overhead Water Tank", topic: "Water Storage & Pumping Systems", difficulty: "Basic", tags: ["storage"],
    definition: "A water storage tank located at the top of a building, used to supply water to fixtures by gravity.",
    function: "To provide adequate pressure to plumbing fixtures through gravity, without relying continuously on pumps.",
    fact: "Overhead tanks are typically filled by transfer pumps from the underground tank and then supply the building by gravity." },
  { term: "Transfer Pump", topic: "Water Storage & Pumping Systems", difficulty: "Basic", tags: ["pumps"],
    definition: "A pump that moves water from an underground tank to an overhead tank or intermediate storage.",
    function: "To replenish the overhead tank so that gravity-fed water supply to fixtures can be maintained.",
    fact: "Transfer pumps are typically controlled by float switches or level sensors in the overhead tank." },
  { term: "Booster Pump", topic: "Water Storage & Pumping Systems", difficulty: "Intermediate", tags: ["pumps"],
    definition: "A pump that increases water pressure in a distribution system to ensure adequate pressure at higher floors or distant fixtures.",
    function: "To provide adequate water pressure where gravity supply alone would be insufficient.",
    fact: "Booster pump sets are commonly used in high-rise buildings to maintain adequate pressure at upper floors." },
  { term: "Hydro-Pneumatic System", topic: "Water Storage & Pumping Systems", difficulty: "Advanced", tags: ["pumps"],
    definition: "A water supply system using a pressurized tank with pumps to maintain water pressure without needing an elevated overhead tank.",
    function: "To provide pressurized water supply where an overhead tank is undesirable due to space, structural, or aesthetic constraints.",
    fact: "Hydro-pneumatic systems use an air cushion within a pressure vessel to maintain consistent supply pressure between pump cycles." },
  { term: "Float Valve", topic: "Water Storage & Pumping Systems", difficulty: "Basic", tags: ["storage"],
    definition: "A valve that automatically controls water level in a tank by closing when a preset level is reached, using a floating device.",
    function: "To prevent tank overflow by automatically stopping water inflow once the tank is full.",
    fact: "Float valves are commonly used in overhead and underground tanks to automatically control filling." },

  // Drainage & Vent Systems
  { term: "Soil Pipe", topic: "Drainage & Vent Systems", difficulty: "Basic", tags: ["drainage"],
    definition: "A drainage pipe that conveys waste from water closets and similar fixtures containing human waste.",
    function: "To safely convey soil waste from fixtures such as water closets to the building drainage system.",
    fact: "Soil pipes are typically sized larger than waste pipes due to the nature and volume of discharge they carry." },
  { term: "Waste Pipe", topic: "Drainage & Vent Systems", difficulty: "Basic", tags: ["drainage"],
    definition: "A drainage pipe that conveys wastewater from fixtures such as wash basins, sinks, and floor drains, excluding soil waste.",
    function: "To convey wastewater from fixtures, excluding water closets, to the building drainage system.",
    fact: "Waste pipes typically connect to the same building drainage system as soil pipes but are classified separately by discharge type." },
  { term: "Vent Pipe (Plumbing)", topic: "Drainage & Vent Systems", difficulty: "Intermediate", tags: ["drainage"],
    definition: "A pipe that allows air to enter or escape a drainage system, maintaining trap seals and preventing pressure fluctuations.",
    function: "To protect fixture trap seals from being siphoned or blown by pressure changes in the drainage system.",
    fact: "Vent pipes typically terminate above roof level to safely release drainage system air to atmosphere." },
  { term: "P-Trap", topic: "Drainage & Vent Systems", difficulty: "Basic", tags: ["drainage"],
    definition: "A curved section of pipe below a plumbing fixture that retains water to form a seal, blocking sewer gases from entering the room.",
    function: "To prevent foul odors and gases from the drainage system from entering occupied spaces.",
    fact: "A P-trap's water seal must be maintained through adequate venting to prevent it from being siphoned dry." },
  { term: "Floor Trap", topic: "Drainage & Vent Systems", difficulty: "Basic", tags: ["drainage"],
    definition: "A trap installed at a floor drain that retains water to block sewer gases while allowing floor wash water to drain.",
    function: "To allow floor wash and incidental water to drain away while blocking odors from the drainage system.",
    fact: "Floor traps require periodic water replenishment, especially in infrequently used areas, to maintain their seal." },
  { term: "Inspection Chamber", topic: "Drainage & Vent Systems", difficulty: "Intermediate", tags: ["drainage"],
    definition: "An accessible chamber provided in an underground drainage system to allow inspection, rodding, and maintenance of pipework.",
    function: "To provide access points for clearing blockages and inspecting underground drainage pipework.",
    fact: "Inspection chambers are typically provided at changes of direction, gradient, or pipe junctions in a drainage system." },

  // Rainwater & Storm Water Drainage
  { term: "Rainwater Downtake Pipe", topic: "Rainwater & Storm Water Drainage", difficulty: "Basic", tags: ["rainwater"],
    definition: "A vertical pipe that conveys rainwater collected from roofs and terraces down to the storm water drainage system.",
    function: "To safely convey collected rainwater from roof and terrace areas to ground-level drainage without causing water ingress.",
    fact: "Rainwater downtake pipes are typically sized based on roof catchment area and local design rainfall intensity." },
  { term: "Storm Water Drainage System", topic: "Rainwater & Storm Water Drainage", difficulty: "Intermediate", tags: ["rainwater"],
    definition: "A system of pipes, channels, and drains that collects and conveys rainwater runoff away from a building or site.",
    function: "To prevent flooding and water accumulation by directing rainwater runoff to an appropriate outfall or storage.",
    fact: "Storm water systems are typically designed for a specific design rainfall intensity and return period." },
  { term: "Rainwater Harvesting", topic: "Rainwater & Storm Water Drainage", difficulty: "Intermediate", tags: ["rainwater"],
    definition: "The collection and storage or groundwater recharge of rainwater for later beneficial use.",
    function: "To conserve water resources by capturing rainwater instead of allowing it to run off as waste.",
    fact: "Rainwater harvesting is often a mandatory requirement in building plan approvals in many jurisdictions." },
  { term: "Roof Drain", topic: "Rainwater & Storm Water Drainage", difficulty: "Basic", tags: ["rainwater"],
    definition: "A drainage outlet fitted at a roof or terrace to collect rainwater and direct it into the rainwater piping system.",
    function: "To efficiently collect roof rainwater while preventing debris from entering and blocking the drainage pipe.",
    fact: "Roof drains are typically fitted with a dome strainer to prevent leaves and debris from entering the pipe." },
  { term: "Percolation Pit", topic: "Rainwater & Storm Water Drainage", difficulty: "Intermediate", tags: ["rainwater"],
    definition: "A pit filled with permeable material that allows collected rainwater to percolate into the ground, recharging groundwater.",
    function: "To recharge groundwater levels by allowing collected rainwater to infiltrate into the soil rather than running off.",
    fact: "Percolation pits are commonly used as part of rainwater harvesting systems to recharge the local water table." },

  // Sewage Treatment (STP/WTP/RO)
  { term: "Sewage Treatment Plant (STP)", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Basic", tags: ["stp"],
    definition: "A facility that treats wastewater from a building or complex to a quality suitable for reuse or safe discharge.",
    function: "To treat sewage to remove contaminants before safe disposal or reuse, such as for flushing or landscaping.",
    fact: "STP-treated water is commonly reused for flushing, gardening, or cooling tower make-up, reducing fresh water demand." },
  { term: "Water Treatment Plant (WTP)", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Basic", tags: ["wtp"],
    definition: "A facility that treats raw or municipal water to improve its quality to potable or process-water standards.",
    function: "To ensure incoming water meets required quality standards before distribution for potable or process use.",
    fact: "A WTP may include processes such as filtration, chlorination, and softening depending on raw water quality." },
  { term: "Reverse Osmosis (RO) System", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Intermediate", tags: ["ro"],
    definition: "A water treatment system that uses a semi-permeable membrane under pressure to remove dissolved solids and impurities from water.",
    function: "To produce high-purity water by removing dissolved salts and contaminants, often for drinking water or process use.",
    fact: "RO systems generate a reject (concentrate) stream in addition to purified permeate water, requiring proper disposal or reuse planning." },
  { term: "Grease Trap", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Basic", tags: ["stp"],
    definition: "A device installed in a kitchen drainage line to intercept and retain grease and oils before they enter the main drainage or STP system.",
    function: "To prevent grease and oil from clogging drainage pipes or overloading the sewage treatment process.",
    fact: "Grease traps require periodic cleaning to remove accumulated grease and maintain effective operation." },
  { term: "Sewage Pump", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Intermediate", tags: ["pumps"],
    definition: "A pump used to lift sewage or wastewater from a lower level, such as a basement, to the main drainage or STP system.",
    function: "To convey wastewater from areas below the gravity drainage invert level up to the point of connection.",
    fact: "Sewage pumps handling raw sewage are typically of a non-clog design suitable for solids-laden wastewater." },
  { term: "Activated Sludge Process", topic: "Sewage Treatment (STP/WTP/RO)", difficulty: "Advanced", tags: ["stp"],
    definition: "A biological sewage treatment process that uses aerated tanks with microorganisms to break down organic matter in wastewater.",
    function: "To biologically treat sewage by using microorganisms to consume organic pollutants under aerobic conditions.",
    fact: "The activated sludge process is one of the most widely used biological treatment methods in sewage treatment plants." },

  // Plumbing Valves & Fixtures
  { term: "Gate Valve", topic: "Plumbing Valves & Fixtures", difficulty: "Basic", tags: ["valves"],
    definition: "A valve that uses a sliding gate to fully open or close a pipeline, typically used for on/off isolation rather than flow regulation.",
    function: "To provide full-bore isolation of a pipeline section for maintenance or shutoff.",
    fact: "Gate valves are generally intended for fully open or fully closed operation, not for throttling flow." },
  { term: "Ball Valve", topic: "Plumbing Valves & Fixtures", difficulty: "Basic", tags: ["valves"],
    definition: "A valve using a rotating ball with a bore to control flow, providing quick quarter-turn on/off operation.",
    function: "To provide quick, reliable isolation for smaller-diameter plumbing pipelines.",
    fact: "Ball valves are commonly used in domestic plumbing due to their compact size and reliable quarter-turn operation." },
  { term: "Check Valve", topic: "Plumbing Valves & Fixtures", difficulty: "Basic", tags: ["valves"],
    definition: "A valve that allows flow in only one direction, automatically closing to prevent backflow.",
    function: "To prevent reverse flow of water, protecting pumps and downstream equipment from backflow damage.",
    fact: "Check valves are commonly installed on the discharge side of pumps to prevent backflow when the pump stops." },
  { term: "Pressure Reducing Valve (PRV)", topic: "Plumbing Valves & Fixtures", difficulty: "Intermediate", tags: ["valves"],
    definition: "A valve that automatically reduces and maintains downstream water pressure at a set value, regardless of upstream pressure variation.",
    function: "To protect plumbing fixtures and pipework from excessive pressure, particularly at lower floors of tall buildings.",
    fact: "PRVs are commonly installed on risers of tall buildings to keep downstream pressure within a safe operating range." },
  { term: "Water Closet (WC)", topic: "Plumbing Valves & Fixtures", difficulty: "Basic", tags: ["fixtures"],
    definition: "A plumbing fixture used for the disposal of human waste, connected to the soil drainage system and flushed with water.",
    function: "To provide sanitary disposal of human waste as part of a building's plumbing system.",
    fact: "Water closets are available in various flushing mechanisms, including single-flush and dual-flush types for water conservation." },
  { term: "Health Faucet", topic: "Plumbing Valves & Fixtures", difficulty: "Basic", tags: ["fixtures"],
    definition: "A hand-held bidet-style spray fixture installed near a water closet for personal hygiene use.",
    function: "To provide a convenient means of personal hygiene using water, common in many regions' bathroom designs.",
    fact: "Health faucets are typically connected to the same water supply line serving the water closet." },

  // Pipe Materials & Selection
  { term: "PPR Pipe", topic: "Pipe Materials & Selection", difficulty: "Basic", tags: ["pipe-materials"],
    definition: "Polypropylene Random Copolymer pipe, commonly used for hot and cold water plumbing due to its heat resistance and corrosion resistance.",
    function: "To convey hot and cold water within a building using a lightweight, corrosion-resistant, heat-fusion-jointed pipe material.",
    fact: "PPR pipes are typically joined by heat fusion welding rather than solvent cement or threading." },
  { term: "CPVC Pipe", topic: "Pipe Materials & Selection", difficulty: "Basic", tags: ["pipe-materials"],
    definition: "Chlorinated Polyvinyl Chloride pipe, used for hot and cold water plumbing with good chemical and temperature resistance.",
    function: "To convey hot and cold water within a building, offering good resistance to scaling and corrosion.",
    fact: "CPVC pipes are typically joined using a solvent cement process rather than heat fusion or threading." },
  { term: "UPVC Pipe", topic: "Pipe Materials & Selection", difficulty: "Basic", tags: ["pipe-materials"],
    definition: "Unplasticized Polyvinyl Chloride pipe, commonly used for cold water supply, drainage, and waste applications.",
    function: "To convey cold water supply or drainage/waste flows using a lightweight, corrosion-resistant plastic pipe.",
    fact: "UPVC pipes are widely used for soil, waste, and rainwater drainage applications due to their smooth bore and corrosion resistance." },
  { term: "HDPE Pipe", topic: "Pipe Materials & Selection", difficulty: "Intermediate", tags: ["pipe-materials"],
    definition: "High-Density Polyethylene pipe, known for flexibility, corrosion resistance, and suitability for buried or long-run water pipelines.",
    function: "To convey water or sewage, particularly in buried, underground, or long-distance pipeline applications.",
    fact: "HDPE pipes are typically joined by butt fusion or electrofusion welding, providing leak-free jointless-like connections." },
  { term: "GI Pipe (Plumbing)", topic: "Pipe Materials & Selection", difficulty: "Basic", tags: ["pipe-materials"],
    definition: "Galvanized Iron pipe, a steel pipe coated with zinc, historically used for water supply plumbing.",
    function: "To convey water supply, offering mechanical strength, though generally more prone to corrosion over time than plastic alternatives.",
    fact: "GI pipes are increasingly being replaced by plastic pipe materials such as CPVC and PPR in modern plumbing installations." },
  { term: "Cast Iron / Ductile Iron Pipe", topic: "Pipe Materials & Selection", difficulty: "Intermediate", tags: ["pipe-materials"],
    definition: "Cast iron or ductile iron pipe, valued for strength and used for soil, waste, and larger drainage applications.",
    function: "To convey soil and waste drainage flows, particularly where mechanical strength or fire-rated drainage risers are required.",
    fact: "Cast iron and ductile iron drainage pipes are commonly used in high-rise buildings for their strength and acoustic performance." },

  // Plumbing Calculations & Sizing
  { term: "Fixture Unit Method", topic: "Plumbing Calculations & Sizing", difficulty: "Advanced", tags: ["sizing"],
    definition: "A method of estimating peak water demand or drainage load by assigning a fixture unit value to each type of plumbing fixture.",
    function: "To size water supply and drainage pipes based on the combined probable simultaneous demand of connected fixtures.",
    fact: "The fixture unit method accounts for the fact that not all fixtures in a building are used simultaneously." },
  { term: "Peak Demand (Water Supply)", topic: "Plumbing Calculations & Sizing", difficulty: "Advanced", tags: ["sizing"],
    definition: "The maximum instantaneous water flow rate a plumbing system must be designed to deliver, accounting for simultaneous fixture usage.",
    function: "To ensure water supply pipes and pumps are sized to meet the highest expected demand without inadequate pressure or flow.",
    fact: "Peak demand is generally much lower than the sum of the maximum flow of every fixture in a building, due to diversity in usage." },
  { term: "Water Supply Pipe Sizing", topic: "Plumbing Calculations & Sizing", difficulty: "Intermediate", tags: ["sizing"],
    definition: "The process of selecting an appropriately sized pipe diameter based on required flow rate and acceptable velocity or pressure loss.",
    function: "To ensure water is delivered at adequate flow and pressure without excessive velocity, noise, or pressure loss.",
    fact: "Water supply pipe velocity is typically limited to a maximum value to control noise and erosion within the pipe." },
  { term: "Drainage Pipe Gradient", topic: "Plumbing Calculations & Sizing", difficulty: "Intermediate", tags: ["sizing"],
    definition: "The slope provided to a drainage pipe to ensure adequate self-cleansing velocity of wastewater flow by gravity.",
    function: "To ensure solids in wastewater are carried along by gravity flow without settling and causing blockages.",
    fact: "Drainage pipes are typically laid to a minimum gradient appropriate to their diameter to maintain self-cleansing velocity." },

  // Plumbing BOQ, Testing & Commissioning
  { term: "Plumbing BOQ", topic: "Plumbing BOQ, Testing & Commissioning", difficulty: "Basic", tags: ["estimation"],
    definition: "A bill of quantities listing pipes, fittings, fixtures, and valves with quantities for pricing a plumbing works package.",
    function: "To provide a standardized basis for pricing and comparing plumbing works packages.",
    fact: "Plumbing BOQs are typically prepared based on approved-for-construction drawings to ensure accurate quantities." },
  { term: "Plumbing Rate Analysis", topic: "Plumbing BOQ, Testing & Commissioning", difficulty: "Intermediate", tags: ["estimation"],
    definition: "A detailed cost breakdown for plumbing items covering pipe, fittings, fixtures, labour, and testing.",
    function: "To establish and justify unit rates quoted for plumbing BOQ items.",
    fact: "Plumbing rate analysis typically accounts for jointing, testing, and fixing labour in addition to material costs." },
  { term: "Pressure Testing (Plumbing)", topic: "Plumbing BOQ, Testing & Commissioning", difficulty: "Intermediate", tags: ["testing"],
    definition: "A test in which a plumbing pipeline is pressurized above its working pressure to check for leaks before it is concealed or commissioned.",
    function: "To verify the integrity of plumbing pipework before it is concealed within walls, floors, or ceilings.",
    fact: "Pressure testing is typically performed and the test pressure held for a specified duration before a pipeline is accepted." },
  { term: "Plumbing Commissioning", topic: "Plumbing BOQ, Testing & Commissioning", difficulty: "Intermediate", tags: ["commissioning"],
    definition: "The process of testing and verifying that plumbing systems and fixtures function correctly and meet design intent before handover.",
    function: "To confirm that installed plumbing systems operate correctly and safely prior to occupancy.",
    fact: "Plumbing commissioning typically includes flow, pressure, and drainage tests at representative fixtures throughout the building." },
];

const num = (n, unit, decimals = 2) => `${Number(n.toFixed(decimals)).toLocaleString("en-IN")} ${unit}`;
const near = (v, pct, rng) => v * (1 + (rng() * 2 - 1) * pct);

const PIPE_SIZE_TABLE = [
  { size: "15 mm", capacityLpm: 15 }, { size: "20 mm", capacityLpm: 30 }, { size: "25 mm", capacityLpm: 55 },
  { size: "32 mm", capacityLpm: 95 }, { size: "40 mm", capacityLpm: 150 }, { size: "50 mm", capacityLpm: 260 },
  { size: "65 mm", capacityLpm: 420 }, { size: "80 mm", capacityLpm: 620 }, { size: "100 mm", capacityLpm: 1050 },
  { size: "150 mm", capacityLpm: 2400 },
];

const CALC_TEMPLATES = [
  {
    name: "domestic-tank-sizing",
    weight: 7,
    spec: {
      discipline: D, topic: "Water Storage & Pumping Systems", subtopic: "Tank Sizing", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => ({ population: randInt(rng, 30, 3000), lpcd: pick(rng, [85, 100, 135, 150, 180]), days: pick(rng, [1, 2]) }),
      compute: ({ population, lpcd, days }) => ({ formatted: num((population * lpcd * days) / 1000, "cu.m", 1), value: (population * lpcd * days) / 1000 }),
      question: ({ population, lpcd, days }) =>
        `A residential building has an estimated population of ${population} persons. Using a design water demand of ${lpcd} litres per capita per day (lpcd) and a required storage of ${days} day(s), what is the minimum required water storage capacity?`,
      explanation: ({ population, lpcd, days }, formatted) =>
        `Storage capacity (cu.m) = (Population x lpcd x Days) / 1000 = (${population} x ${lpcd} x ${days}) / 1000 = ${formatted}.`,
      distractors: ({ population, lpcd, days }, result, rng) => [
        num(result.value / 2, "cu.m", 1),
        num(result.value * 1.6, "cu.m", 1),
        num(near(result.value, 0.25, rng), "cu.m", 1),
      ],
    },
  },
  {
    name: "pipe-velocity-diameter",
    weight: 6,
    spec: {
      discipline: D, topic: "Plumbing Calculations & Sizing", subtopic: "Pipe Sizing by Velocity", tags: ["calculation"], difficulty: "Advanced",
      gen: (rng) => ({ flowLps: randFloat(rng, 0.5, 25, 2), velocity: randFloat(rng, 1.0, 2.2, 1) }),
      compute: ({ flowLps, velocity }) => {
        const areaM2 = (flowLps / 1000) / velocity;
        const diameterMm = Math.sqrt((4 * areaM2) / Math.PI) * 1000;
        return { formatted: num(diameterMm, "mm", 1), value: diameterMm };
      },
      question: ({ flowLps, velocity }) =>
        `A water supply pipe must carry a flow of ${flowLps} l/s while keeping velocity within a design limit of ${velocity} m/s. What is the approximate minimum internal pipe diameter required?`,
      explanation: ({ flowLps, velocity }, formatted) =>
        `Required area = Flow(m3/s) / Velocity. Diameter = sqrt(4 x Area / pi). For ${flowLps} l/s at ${velocity} m/s, the approximate minimum diameter is ${formatted}.`,
      distractors: ({ flowLps, velocity }, result, rng) => [
        num(result.value * 1.7, "mm", 1),
        num(result.value / 1.7, "mm", 1),
        num(near(result.value, 0.25, rng), "mm", 1),
      ],
    },
  },
  {
    name: "pipe-size-selection",
    weight: 5,
    spec: {
      discipline: D, topic: "Plumbing Calculations & Sizing", subtopic: "Pipe Size Selection", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => {
        const idx = randInt(rng, 1, PIPE_SIZE_TABLE.length - 2);
        const requiredFlow = randInt(rng, PIPE_SIZE_TABLE[idx - 1].capacityLpm + 1, PIPE_SIZE_TABLE[idx].capacityLpm - 1);
        return { idx, requiredFlow };
      },
      compute: ({ idx }) => ({ formatted: PIPE_SIZE_TABLE[idx].size, value: idx }),
      question: ({ requiredFlow }) =>
        `A branch water supply line must carry a design flow of ${requiredFlow} litres per minute. Given standard pipe capacities of 15mm/15lpm, 20mm/30lpm, 25mm/55lpm, 32mm/95lpm, 40mm/150lpm, 50mm/260lpm, 65mm/420lpm, and 80mm/620lpm, what is the smallest adequate pipe size?`,
      explanation: ({ idx, requiredFlow }, formatted) =>
        `The selected pipe's rated capacity must equal or exceed the design flow of ${requiredFlow} lpm. ${formatted} is the smallest standard size meeting this requirement.`,
      distractors: ({ idx }) => {
        const opts = [];
        if (PIPE_SIZE_TABLE[idx - 1]) opts.push(PIPE_SIZE_TABLE[idx - 1].size);
        if (PIPE_SIZE_TABLE[idx + 1]) opts.push(PIPE_SIZE_TABLE[idx + 1].size);
        if (PIPE_SIZE_TABLE[idx + 2]) opts.push(PIPE_SIZE_TABLE[idx + 2].size);
        return opts.slice(0, 3);
      },
    },
  },
  {
    name: "stp-capacity-sizing",
    weight: 6,
    spec: {
      discipline: D, topic: "Sewage Treatment (STP/WTP/RO)", subtopic: "STP Sizing", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => ({ population: randInt(rng, 100, 5000), flowPerCapita: pick(rng, [90, 100, 110, 120, 135]) }),
      compute: ({ population, flowPerCapita }) => ({
        formatted: num((population * flowPerCapita) / 1000, "cu.m/day", 1),
        value: (population * flowPerCapita) / 1000,
      }),
      question: ({ population, flowPerCapita }) =>
        `A residential complex has an estimated population of ${population} persons, generating sewage at ${flowPerCapita} litres per capita per day (typically about 80-135% of water supply). What is the approximate design capacity required for the STP?`,
      explanation: ({ population, flowPerCapita }, formatted) =>
        `STP design capacity (cu.m/day) = (Population x sewage generation rate) / 1000 = (${population} x ${flowPerCapita}) / 1000 = approximately ${formatted}.`,
      distractors: ({ population, flowPerCapita }, result, rng) => [
        num(result.value / 2, "cu.m/day", 1),
        num(result.value * 1.6, "cu.m/day", 1),
        num(near(result.value, 0.25, rng), "cu.m/day", 1),
      ],
    },
  },
  {
    name: "rainwater-downpipe-sizing",
    weight: 5,
    spec: {
      discipline: D, topic: "Rainwater & Storm Water Drainage", subtopic: "Rainwater Downpipe Sizing", tags: ["calculation"], difficulty: "Advanced",
      gen: (rng) => ({ roofArea: randInt(rng, 50, 3000), intensity: pick(rng, [50, 75, 100, 125, 150]) }),
      compute: ({ roofArea, intensity }) => {
        const flowLps = (roofArea * intensity) / 3600;
        return { formatted: num(flowLps, "l/s", 2), value: flowLps };
      },
      question: ({ roofArea, intensity }) =>
        `A roof catchment area of ${roofArea} sq.m must be drained during a design rainfall intensity of ${intensity} mm/hr. What is the approximate design rainwater flow rate that the rainwater pipes must be sized to carry?`,
      explanation: ({ roofArea, intensity }, formatted) =>
        `Design flow (l/s) = (Roof area(sq.m) x Rainfall intensity(mm/hr)) / 3600 = (${roofArea} x ${intensity}) / 3600 = approximately ${formatted}.`,
      distractors: ({ roofArea, intensity }, result, rng) => [
        num(result.value * 2, "l/s", 2),
        num(result.value / 2, "l/s", 2),
        num(near(result.value, 0.3, rng), "l/s", 2),
      ],
    },
  },
  {
    name: "booster-pump-power",
    weight: 6,
    spec: {
      discipline: D, topic: "Water Storage & Pumping Systems", subtopic: "Booster Pump Power", tags: ["calculation"], difficulty: "Advanced",
      gen: (rng) => ({ flowLps: randInt(rng, 2, 60), head: randInt(rng, 20, 90), eff: randFloat(rng, 0.55, 0.72, 2) }),
      compute: ({ flowLps, head, eff }) => {
        const kw = (flowLps * head * 9.81) / (1000 * eff);
        return { formatted: num(kw, "kW", 2), value: kw };
      },
      question: ({ flowLps, head, eff }) =>
        `A domestic booster pump delivers ${flowLps} l/s against a total head of ${head} m, with a pump efficiency of ${eff}. What is the approximate shaft power required?`,
      explanation: ({ flowLps, head, eff }, formatted) =>
        `Power (kW) = (Flow(l/s) x Head(m) x 9.81) / (1000 x efficiency) = (${flowLps} x ${head} x 9.81) / (1000 x ${eff}) = approximately ${formatted}.`,
      distractors: ({ flowLps, head, eff }, result, rng) => [
        num(result.value * 1.7, "kW", 2),
        num(result.value / 2, "kW", 2),
        num(near(result.value, 0.3, rng), "kW", 2),
      ],
    },
  },
  {
    name: "tank-fill-time",
    weight: 5,
    spec: {
      discipline: D, topic: "Water Storage & Pumping Systems", subtopic: "Tank Fill Time", tags: ["calculation"], difficulty: "Basic",
      gen: (rng) => ({ capacity: randInt(rng, 2000, 60000), inflowLpm: randInt(rng, 100, 2000) }),
      compute: ({ capacity, inflowLpm }) => ({ formatted: num(capacity / inflowLpm / 60, "hours", 2), value: capacity / inflowLpm / 60 }),
      question: ({ capacity, inflowLpm }) =>
        `An overhead tank of ${capacity} litres capacity is filled by a transfer pump delivering ${inflowLpm} litres per minute. Approximately how long will it take to fill the empty tank?`,
      explanation: ({ capacity, inflowLpm }, formatted) =>
        `Fill time (hours) = Capacity / (Inflow rate x 60) = ${capacity} / (${inflowLpm} x 60) = approximately ${formatted}.`,
      distractors: ({ capacity, inflowLpm }, result, rng) => [
        num(result.value * 2, "hours", 2),
        num(result.value / 2, "hours", 2),
        num(near(result.value, 0.3, rng), "hours", 2),
      ],
    },
  },
  {
    name: "ro-recovery-permeate",
    weight: 5,
    spec: {
      discipline: D, topic: "Sewage Treatment (STP/WTP/RO)", subtopic: "RO Recovery", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => ({ feedLph: randInt(rng, 200, 10000), recovery: pick(rng, [50, 60, 65, 70, 75]) }),
      compute: ({ feedLph, recovery }) => ({ formatted: num((feedLph * recovery) / 100, "lph", 0), value: (feedLph * recovery) / 100 }),
      question: ({ feedLph, recovery }) =>
        `An RO plant is fed with raw water at ${feedLph} litres per hour and operates at a recovery ratio of ${recovery}%. What is the approximate permeate (purified water) output rate?`,
      explanation: ({ feedLph, recovery }, formatted) =>
        `Permeate output = Feed flow x Recovery ratio = ${feedLph} x ${recovery}% = approximately ${formatted}. The remainder is discharged as reject/concentrate.`,
      distractors: ({ feedLph, recovery }, result, rng) => [
        num(feedLph - result.value, "lph", 0),
        num(result.value * 1.5, "lph", 0),
        num(near(result.value, 0.25, rng), "lph", 0),
      ],
    },
  },
  {
    name: "wc-count-from-occupancy",
    weight: 4,
    spec: {
      discipline: D, topic: "Plumbing Valves & Fixtures", subtopic: "Fixture Count", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => ({ occupants: randInt(rng, 20, 800), ratio: pick(rng, [15, 20, 25, 30]) }),
      compute: ({ occupants, ratio }) => ({ formatted: `${Math.ceil(occupants / ratio)} WCs`, value: Math.ceil(occupants / ratio) }),
      question: ({ occupants, ratio }) =>
        `An office floor has ${occupants} occupants of one gender. If the design ratio requires one water closet for every ${ratio} occupants, what is the minimum number of water closets required for this floor?`,
      explanation: ({ occupants, ratio }, formatted) =>
        `Minimum WCs = Occupants / Ratio per WC, rounded up = ${occupants} / ${ratio} rounded up to ${formatted}.`,
      distractors: ({ occupants, ratio }, result, rng) => [
        `${Math.max(1, result.value - 2)} WCs`,
        `${result.value + 3} WCs`,
        `${Math.max(1, Math.round(near(result.value, 0.3, rng)))} WCs`,
      ],
    },
  },
  {
    name: "water-bill-cost",
    weight: 4,
    spec: {
      discipline: D, topic: "Domestic Water Supply", subtopic: "Water Cost", tags: ["calculation", "estimation"], difficulty: "Basic",
      gen: (rng) => ({ consumption: randInt(rng, 50, 5000), rate: randFloat(rng, 20, 60, 1) }),
      compute: ({ consumption, rate }) => ({ formatted: `Rs ${Math.round(consumption * rate).toLocaleString("en-IN")}`, value: consumption * rate }),
      question: ({ consumption, rate }) =>
        `A building consumes ${consumption} cu.m of water in a billing period. At a water tariff of Rs ${rate} per cu.m, what is the approximate total water bill for the period?`,
      explanation: ({ consumption, rate }, formatted) => `Total cost = Consumption x Rate = ${consumption} x ${rate} = ${formatted}.`,
      distractors: ({ consumption, rate }, result, rng) => [
        `Rs ${Math.round(result.value / 2).toLocaleString("en-IN")}`,
        `Rs ${Math.round(result.value * 1.6).toLocaleString("en-IN")}`,
        `Rs ${Math.round(near(result.value, 0.25, rng)).toLocaleString("en-IN")}`,
      ],
    },
  },
  {
    name: "plumbing-boq-cost",
    weight: 4,
    spec: {
      discipline: D, topic: "Plumbing BOQ, Testing & Commissioning", subtopic: "Rate Analysis", tags: ["calculation", "estimation"], difficulty: "Basic",
      gen: (rng) => ({ qty: randInt(rng, 20, 900), rate: randInt(rng, 150, 3200), unit: pick(rng, ["m", "nos", "sq.m"]) }),
      compute: ({ qty, rate }) => ({ formatted: `Rs ${(qty * rate).toLocaleString("en-IN")}`, value: qty * rate }),
      question: ({ qty, rate, unit }) =>
        `A plumbing BOQ item has a measured quantity of ${qty} ${unit} at a finalized rate of Rs ${rate} per ${unit}. What is the total cost for this BOQ item?`,
      explanation: ({ qty, rate }, formatted) => `Total cost = Quantity x Rate = ${qty} x ${rate} = ${formatted}.`,
      distractors: ({ qty, rate }, result, rng) => [
        `Rs ${Math.round(result.value / 2).toLocaleString("en-IN")}`,
        `Rs ${Math.round(result.value * 1.5).toLocaleString("en-IN")}`,
        `Rs ${Math.round(near(result.value, 0.25, rng)).toLocaleString("en-IN")}`,
      ],
    },
  },
  {
    name: "drainage-gradient-drop",
    weight: 3,
    spec: {
      discipline: D, topic: "Plumbing Calculations & Sizing", subtopic: "Drainage Gradient", tags: ["calculation"], difficulty: "Intermediate",
      gen: (rng) => ({ length: randInt(rng, 5, 90), gradient: pick(rng, [40, 60, 90, 100, 120]) }),
      compute: ({ length, gradient }) => ({ formatted: num((length * 1000) / gradient, "mm", 0), value: (length * 1000) / gradient }),
      question: ({ length, gradient }) =>
        `A drainage pipe run of ${length} m length is laid to a gradient of 1 in ${gradient}. What is the total fall (drop in level) required over this run?`,
      explanation: ({ length, gradient }, formatted) =>
        `Total fall = (Length x 1000) / Gradient denominator = (${length} x 1000) / ${gradient} = approximately ${formatted}.`,
      distractors: ({ length, gradient }, result, rng) => [
        num(result.value * 2, "mm", 0),
        num(result.value / 2, "mm", 0),
        num(near(result.value, 0.3, rng), "mm", 0),
      ],
    },
  },
];

export function generatePlumbing() {
  const conceptual = roundRobinTrim(buildFromFactBank(FACTS, D), CONCEPTUAL_TARGET, (q) => q.topic);
  const calcTarget = TARGET - conceptual.length;
  const calc = buildCalcSet(CALC_TEMPLATES, calcTarget, "plumbing");
  return [...conceptual, ...calc].slice(0, TARGET);
}
